### ISSUE TITLE
Incorrect bun version: 0.5.6

### ISSUE THREAD

**Issue by vkzrx** [oven-sh/setup-bun#19]
Hello,

The wrong bun version is downloaded whether the version is specified or not.
It was working fine until very recently (~1h)
I'm always getting `v0.5.6` which seems broken for workspaces

I'm using a minimal config

```yml
name: CI

on:
  pull_request:
  push:

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.0

      - name: Install Dependencies
        run: bun install

      - name: Run
        run: bun run index.ts
```

I have a minimal repo here: https://github.com/0xYami/bun-repro-ci-bun-version

Log without version specified (should defaults to `latest`): https://github.com/0xYami/bun-repro-ci-bun-version/actions/runs/6151432253/job/16691465674#step:3:30

Log with version specified (should be `1.0.0`): https://github.com/0xYami/bun-repro-ci-bun-version/actions/runs/6151502117/job/16691677799#step:3:31

**Comment by chrissiwaffler** [comment]
got the same problem!

deleting the caches of github action also doesn't solve the issue, neither does changing the underlying OS (e.g., `ubuntu-latest`, `macos-latest`)

**Comment by Electroid** [comment]
Can you re-run the CI's? This should have been fixed

**Comment by fobo66** [comment]
Still reproducible for me: https://github.com/fobo66/algolia-firebase-functions/actions/runs/6151611228/job/16692147285?pr=617

**Comment by chrissiwaffler** [comment]
@Electroid 
No, no change on my side.
I just deleted the cache and rerun with debug logging:
```
##[debug]Commiting cache
Cache Size: ~29 MB (303[79](https://github.com/StargazerLabs/on-off-chain/actions/runs/6151569066/job/16692120633#step:3:79)347 B)
##[debug]Resource Url: https://acghubeus2.actions.githubusercontent.com/yUl1bynyqSJICpPVLJ5jzo73W0rmen6e14pYDpr0dViKA7pqXI/_apis/artifactcache/caches/20
Cache saved successfully
##[debug]Node Action run completed with exit code 0
##[debug]Set output bun-version = 0.5.6
##[debug]Set output bun-revision = 0.5.6
##[debug]Set output cache-hit = false
##[debug]Finishing: Setup Bun
```

**Comment by vkzrx** [comment]
Still reproducible for me too

**Comment by Electroid** [comment]
Looking into right now

**Comment by Electroid** [comment]
OK, hot-fix pushed. Please try again.

**Comment by fobo66** [comment]
Looks like it worked: https://github.com/fobo66/algolia-firebase-functions/actions/runs/6151611228/job/16692278562

Thanks!

**Comment by chrissiwaffler** [comment]
Yes it works, thanks for the superfast fix 🏃

**Comment by Platane** [comment]
That was some fast reactivity ! thanks

**Comment by Electroid** [comment]
Apologies for those that ran into this issue. This happened because there wasn't an automated script to update the `v1` tag, so it was done manually and I made a mistake. We will make sure this is automated next time. (and with CI, of course)

**Comment by vkzrx** [comment]
Yeah it works now! Thank you so much
