### ISSUE TITLE
Custom registry-url and scope not working

### ISSUE THREAD

**Issue by JakobLierman** [oven-sh/setup-bun#33]
I have the following step:
```yaml
- name: Use Bun v1
  uses: oven-sh/setup-bun@v1
  with:
    registry-url: "https://npm.pkg.github.com"
    scope: "@companyName"
```

In the logs, I get this warning: `Unexpected input(s) 'registry-url', 'scope', valid inputs are ['bun-version']`.

There are [setup instructions](https://github.com/oven-sh/setup-bun?tab=readme-ov-file#setup-custom-registry-url-and-scope-for-private-packages) available in the README.md file, but this doesn't seem to reflect what's actually deployed. I can also see some work being done in the commit logs, seems like some runners are throwing an error.

**Comment by JakobLierman** [comment]
Looks like it's just a warning that hasn't been removed.

Whilst installing my dependencies, it uses the correct registry. It however throws a 401 error, even though the `BUN_AUTH_TOKEN` is being set correctly.

```yaml
- name: Install dependencies
  env:
    BUN_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run: bun install --frozen-lockfile
```

Error on the install step: `GET https://npm.pkg.github.com/download/@companyName/eslint-config/1.0.0/[...] - 401`

**Comment by praveenpuglia** [comment]
I did the same but I get the following error
```
error: FailedToOpenSocket downloading tarball @myorg/my-package@0.7.0
```

for all the `@myorg` scoped packages. Would GITHUB_TOKEN not work and I have to create a separate token for this?

**Comment by vitoorgomes** [comment]
> Looks like it's just a warning that hasn't been removed.
> 
> Whilst installing my dependencies, it uses the correct registry. It however throws a 401 error, even though the `BUN_AUTH_TOKEN` is being set correctly.
> 
> ```yaml
> - name: Install dependencies
>   env:
>     BUN_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
>   run: bun install --frozen-lockfile
> ```
> 
> Error on the install step: `GET https://npm.pkg.github.com/download/@companyName/eslint-config/1.0.0/[...] - 401`

howdy 👋🏼  I was the one that implemented this feature, but for what I'm seeing, when it was merged, it didn't create a new release, so using `oven-sh/setup-bun@v1` is still using the outdated version

when it's working, the warning should be removed, as well as showing as a log on job step (line 10) this screenshot is from my private testing before merging #16 

<img width="747" alt="image" src="https://github.com/oven-sh/setup-bun/assets/41302394/06a25634-0a93-425c-a969-dfde34211b76">

@xHyroM @Electroid would be possible to manually generate a new release version with source code from main branch?

**Comment by vitoorgomes** [comment]
> I did the same but I get the following error
> 
> ```
> error: FailedToOpenSocket downloading tarball @myorg/my-package@0.7.0
> ```
> 
> for all the `@myorg` scoped packages. Would GITHUB_TOKEN not work and I have to create a separate token for this?

aside from the previous comment about the action problem, you need to make sure that your token has access to private packages/repos, when this action get a new release you will be able to test it properly

**Comment by praveenpuglia** [comment]
@vitoorgomes hey! I have made sure the token has access! Waiting for the release! 🙌

**Comment by vitoorgomes** [comment]
hey guys @praveenpuglia @JakobLierman I totally forgot that you can use github actions versions in different ways

tags are the best option for control over things, but you can also use any branch name or even a commit sha

although you don't have a good control when using the branch name, you can do it, so you guys don't have to wait the release version, the step would be something like this

```
      - uses: oven-sh/setup-bun@main # or @commit_sha
        with:
          bun-version: latest
          registry-url: 'https://npm.pkg.github.com'  # or any registry url that you guys have
          scope: '@foo-bar'
```

hope this helps 😄 

ps: I think it's still good to keep this issue so the version using tags would be published and we stop using `@main`

**Comment by JakobLierman** [comment]
Using version tags would indeed be a great improvement. Will use the branch for now.

Some more docs on semantic versioning: https://semver.org/.
You can use [Semantic Release](https://github.com/semantic-release/semantic-release) to automate this.

**Comment by xhyrom** [comment]
I'll release new version of this action to make everything easier 👍

**Comment by samuellawerentz** [comment]
Hi @xHyroM and @vitoorgomes 

I'm getting this error while running install step `bun install`, is there something that I need to change? Any help is appreciated. Thanks
![image](https://github.com/oven-sh/setup-bun/assets/51610898/fa60fa33-9432-4a8d-a696-6dc1121cf740)


This error is thrown from this line I guess - https://github.com/oven-sh/bun/blob/85c997513d2b05acab21e758512954273e3a589a/src/toml/toml_parser.zig#L265

**Comment by samuellawerentz** [comment]
Okay, I was able to get past this issue, once I deleted `bunfig.toml` from my repo. 
But I need it to be there so that people can install private packages.
Can we use the existing `bunfig.toml` instead of creating it during execution?

**Comment by vitoorgomes** [comment]
> Hi @xHyroM and @vitoorgomes
> 
> I'm getting this error while running install step `bun install`, is there something that I need to change? Any help is appreciated. Thanks ![image](https://user-images.githubusercontent.com/51610898/283531278-fa60fa33-9432-4a8d-a696-6dc1121cf740.png)
> 
> This error is thrown from this line I guess - https://github.com/oven-sh/bun/blob/85c997513d2b05acab21e758512954273e3a589a/src/toml/toml_parser.zig#L265

for what I'm seeing is that the action is not being able to extend the project local `bunfig.toml` because it already have the registry key, I know where to fix it and I will try to submit a PR soon to extend instead of trying to rewrite the `[install.scopes]` section

> Okay, I was able to get past this issue, once I deleted `bunfig.toml` from my repo. But I need it to be there so that people can install private packages. Can we use the existing `bunfig.toml` instead of creating it during execution?

you can achieve this by creating a global bunfig file and moving the `[install.scopes]` section over there, that way, every time you try to install dependencies it will merge both local and global configs, and in my opinion this is the best option because you can hide the github token from the repo and it will only exists on your machine and each developer should have one of that, similar to `.npmrc` that can also exists both global and local

[more about it](https://bun.sh/docs/runtime/bunfig#global-vs-local)

**Comment by praveenpuglia** [comment]
we gave up on this because we were just unable to install any private package using this action. Tried the latest action via the hash in the action version. 

NPM was able to install all the packages just fine with an npmrc and the exact same token.

**Comment by xhyrom** [comment]
Should be fixed in latest version

**Comment by samuellawerentz** [comment]
Still getting that error.

![image](https://github.com/user-attachments/assets/420e32e2-49da-49f9-8986-1ee9a842ad13)
