### ISSUE TITLE
Version selectors `1.x`/`1.0.x` result in `400/404` response errors on install

### ISSUE THREAD

**Issue by byCedric** [oven-sh/setup-bun#37]
We use bun in various parts of the expo/expo repository, e.g. [here](https://github.com/expo/expo/blob/main/.github/workflows/cli.yml#L53-L56). Like the node setup action, we use a version selector with a `.x`, e.g., `node-version: 18.x`.

This seemed to work until some days ago when our CI started failing with the following message:
<img width="753" alt="image" src="https://github.com/oven-sh/setup-bun/assets/1203991/ac7c62b6-ea9b-4a47-89f9-3f6e42acf1eb">

A quick test showed that using the exact version number does seem to work, but `1.x` or `1.0.x` won't anymore. Is this something that never should have worked, or a bug? 😄 

request | response
---     | ---
`1.0.x` | ![using `1.0.x` as version](https://github.com/oven-sh/setup-bun/assets/1203991/6d43f511-5421-44b3-b748-732b1af434bb)
`1.x` | ![using `1.x` as version](https://github.com/oven-sh/setup-bun/assets/1203991/934712ab-16e2-4cdc-8366-eb16a8dbee9f)
`1.0.11` | _✅ - but big image, see below_
`latest` | _✅ - but big image, see below_

<details><summary>See <code>1.0.11</code> response</summary>

![using `1.0.11` as version](https://github.com/oven-sh/setup-bun/assets/1203991/89295f33-81ae-4344-a925-3ec47f21d2db)

</details>

<details><summary>See <code>latest</code> response</summary>

![using `latest` as version](https://github.com/oven-sh/setup-bun/assets/1203991/9db82832-351a-4bd2-818a-51d40b0b32eb)

</details>

**Comment by byCedric** [comment]
If this shouldn't have worked from the start, consider adding it 😄 The benefit of `bun-version: 1.x` over `bun-version: 1` is that YAML (& tooling) will cast the value as a string instead of a number.

**Comment by xhyrom** [comment]
This is an issue with bun's api, sadly, I can't do anything with it. Electorid must solve it.

**Comment by byCedric** [comment]
I'd figure as much 😄 Thanks for pulling in the right person to solve it.

**Comment by Electroid** [comment]
We actually think this could be a bug in Bun. These errors are not from Github, we're investigating.

**Comment by xhyrom** [comment]
Looks like this is already fixed.

**Comment by na-ji** [comment]
> Looks like this is already fixed.

It isn't. It's giving a different error now. When I try 1.x, I get this 404 error:

```
Run oven-sh/setup-bun@v1
  with:
    bun-version: 1.x
    no-cache: false
Downloading a new version of Bun: https://bun.sh/download/1.x/linux/x64?avx2=true&profile=false
Error: Error: Unexpected HTTP response: 404
```

I guess we should re-open this issue. And maybe link it to an issue on bun side?

**Comment by xhyrom** [comment]
> > Looks like this is already fixed.
> 
> It isn't. It's giving a different error now. When I try 1.x, I get this 404 error:
> 
> ```
> Run oven-sh/setup-bun@v1
>   with:
>     bun-version: 1.x
>     no-cache: false
> Downloading a new version of Bun: https://bun.sh/download/1.x/linux/x64?avx2=true&profile=false
> Error: Error: Unexpected HTTP response: 404
> ```
> 
> I guess we should re-open this issue. And maybe link it to an issue on bun side?

I tried it and it works. Maybe you can try again? :D

**Comment by Zeryther** [comment]
![image](https://github.com/oven-sh/setup-bun/assets/5731334/2ec7f7e5-941a-4a72-9450-818555365613)

Also failing for "1.x"

**Comment by xhyrom** [comment]
> ![image](https://private-user-images.githubusercontent.com/5731334/329295577-2ec7f7e5-941a-4a72-9450-818555365613.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNzA5ODYsIm5iZiI6MTcxNTI3MDY4NiwicGF0aCI6Ii81NzMxMzM0LzMyOTI5NTU3Ny0yZWM3ZjdlNS05NDFhLTRhNzItOTQ1MC04MTg1NTUzNjU2MTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDlUMTYwNDQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2M2YmExZmI2OTY2Yzk3YWVhMGY5ZGY2Mzg4NzI1ODI4ZjZiYTk2ODZiZjg2ZDA1ZTRhYjc5OWFmOTM5MjJjZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QWVssrZiBQH4DJ0in3qVVWtg4_PeKTBCnEh_04bK8sw)
> 
> Also failing for "1.x"

~~can you send the details please? (click on the first line)~~
don't have to ;)

**Comment by xhyrom** [comment]
Something is wrong with bun's download api again. https://github.com/oven-sh/setup-bun/actions/runs/9020175817

**Comment by jerome-benoit** [comment]
The issue seems triggered each time a bun new version is in the release pipeline: new version seems to be announced to the download system before the pipeline has finished and binaries are available. And fallback to previous matching latest version does not seem to work.

**Comment by jerome-benoit** [comment]
> The issue seems triggered each time a bun new version is in the release pipeline: new version seems to be announced to the download system before the pipeline has finished and binaries are available. And fallback to previous matching latest version does not seem to work.

The error pattern seems more related to a call to an API that is rate limited if the version contains some kind of wildcard.  It seems to involve a call to a rate limited API to get a list of the available bun versions which is failing.

**Comment by xhyrom** [comment]
> > The issue seems triggered each time a bun new version is in the release pipeline: new version seems to be announced to the download system before the pipeline has finished and binaries are available. And fallback to previous matching latest version does not seem to work.
> 
> The error pattern seems more related to a call to an API that is rate limited if the version contains some kind of wildcard. It seems to involve a call to a rate limited API get a list of the available bun versions which is failing.

I'm considering implementing wildcard resolution into the action itself instead of using API for it. It would resolve all the issues we're currently facing.

**Comment by jerome-benoit** [comment]
> I'm considering implementing wildcard resolution into the action itself instead of using API for it. It would resolve all the issues we're currently facing.

With a static file containing all the shipped bun versions like https://nodejs.org/download/release/index.json, it will allow tools like setup-bun to get it, cache it and refresh it only if needed. Adding its generation to the bun release process should not be too hard. Adding a way to get its content hash will help tools at knowing if a refresh is needed.

**Comment by deerranged** [comment]
Just ran into this issue on a private repository while using the `1.x` selector. I went with Cedric's fix and changed it into `latest`.

As far as I'm aware, this shouldn't be a hard thing to fix, so let's hope for the best I guess.

**Comment by xhyrom** [comment]
Pull request https://github.com/oven-sh/setup-bun/pull/93 should resolve all issues related to this. Anybody can try the development version of setup-bun by using `oven-sh/setup-bun@feat/implement-wildcard-resolution-into-the-action` (i hope that reference works)

**Comment by typed-sigterm** [comment]
Not only `1.x`, `1` will fail also

**Comment by afonsojramos** [comment]
Can confirm that this is also happening if the x is for the patch.

```sh
Run oven-sh/setup-bun@v2
Obtained version 1.2.x from .bun-version
Downloading a new version of Bun: https://bun.sh/download/1.2.x/linux/x64?avx2=true&profile=false
Error: Error: Unexpected HTTP response: 400
```

**Edit:** And from the last runs of the integration tests it seems that everyone is aware of it: https://github.com/oven-sh/setup-bun/actions/runs/13141349674

**Comment by xhyrom** [comment]
> Can confirm that this is also happening if the x is for the patch.
> 
> Run oven-sh/setup-bun@v2
> Obtained version 1.2.x from .bun-version
> Downloading a new version of Bun: https://bun.sh/download/1.2.x/linux/x64?avx2=true&profile=false
> Error: Error: Unexpected HTTP response: 400
> **Edit:** And from the last runs of the integration tests it seems that everyone is aware of it: https://github.com/oven-sh/setup-bun/actions/runs/13141349674

This is a known feature, but it’s not a priority for the core team. Unfortunately, I don’t have access to Bun’s external API, so I submitted a PR to remove its usage (https://github.com/oven-sh/setup-bun/pull/93), but it was closed. I’m not sure how long it'll take them to solve this. :/

**Comment by afonsojramos** [comment]
@Jarred-Sumner sorry for the ping, but. Is there any way we can get help with this?

In the meantime, we could at least remove the wildcard from the readme, would that be okay? https://github.com/oven-sh/setup-bun/blob/main/README.md?plain=1#L57

**Comment by LitoMore** [comment]
I've created a proposal for a release workflow to avoid this problem:

- https://github.com/oven-sh/setup-bun/issues/125

**Comment by xhyrom** [comment]
> I've created a proposal for a release workflow to avoid this problem:
> 
> * [Create a v2 branch instead of moving the tag #125](https://github.com/oven-sh/setup-bun/issues/125)

This issue has nothing to do with the proposal you made.

**Comment by LitoMore** [comment]
> This issue has nothing to do with the proposal you made.

Ah, sorry, I just misunderstood this.

**Comment by afonsojramos** [comment]
@Electroid can you take another look? I think that from all the discussion taken above, the issue is clearly with the api.

If you go to this link `https://bun.sh/download/1.2.x/linux/x64?avx2=true&profile=false` you'll get a 401, because the api is not able to get the latest 1.2.x release.

**Comment by xhyrom** [comment]
> [@Electroid](https://github.com/Electroid) can you take another look? I think that from all the discussion taken above, the issue is clearly with the api.
> 
> If you go to this link `https://bun.sh/download/1.2.x/linux/x64?avx2=true&profile=false` you'll get a 401, because the api is not able to get the latest 1.2.x release.

This is a well-known problem by the team (https://github.com/oven-sh/setup-bun/pull/93#issuecomment-2258103830)

**Comment by bimohenokh** [comment]
is this fixed now? i still got the same error

- name: Setup Bun
  uses: oven-sh/setup-bun@v2
  with:
    bun-version: 1.2.x

Run oven-sh/setup-bun@v2
Downloading a new version of Bun: https://bun.sh/download/1.2.x/linux/x64?avx2=true&profile=false
Error: Error: Unexpected HTTP response: 400

**Comment by xhyrom** [comment]
This open is open,  that means it's still not fixed. Unfortunately, I can't do anything about it.

**Comment by bimohenokh** [comment]
Ah okay, I see. I’m new to this type of conversation, so I might need a bit of guidance.

**Comment by xhyrom** [comment]
finally done; sorry for the delay. will be included in next release.
